<?php

return [
    'title' => 'Settings',
    'navigation_label' => 'Settings',

    'description' => 'This information is printed on invoices, receipts and the delivery act. It is stored once and every document uses it.',

    'sections' => [
        'business' => 'Business details',
        'contact' => 'Contact',
        'billing' => 'Billing',
        'inventory' => 'Spaces catalog',
    ],

    'descriptions' => [
        'billing' => 'These documents are not electronic invoices certified by the DIAN.',
        'inventory' => 'One space per line. Used to group the delivery act inventory.',
    ],

    'form' => [
        'business_name' => 'Company name',
        'tax_id' => 'Tax ID',
        'address' => 'Address',
        'currency' => 'Currency',
        'logo' => 'Logo',
        'email' => 'Notification email',
        'phone' => 'Phone',
        'invoice_due_days' => 'Invoice due days',
        'legal_footer' => 'Legal footer text',
        'space_catalog' => 'Spaces',
    ],

    'placeholders' => [
        'business_name' => 'Example Real Estate LLC',
        'tax_id' => '900.123.456-7',
        'legal_footer' => 'Document generated by the rental management system. It is not an electronic invoice.',
    ],

    'buttons' => [
        'save' => 'Save settings',
    ],

    'saved' => 'Settings saved',
];